#!/bin/bash

# Execute Fetch


# Execute Translate
java org.vivoweb.ingest.translate.xsltranslate -rh "\config\recordHandlers\TranslateInPubmedXMLRecordHandler.xml" "\DataMaps\PubMedToXML.xsl" "\config\recordHandlers\TranslateOutPubmedRecordHandler.xml"

# Execute Score
java -jar harvester.jar score "\config\ScoringInXMLRecordHandler.xml" "\config\ScpringVIVOInput.xml" "\config\SoringJenaInput.xml"

# Execute Qualify


# Execute Transfer